# PyTorch Basic
- https://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html

# 1. Tensors

In [1]:
from __future__ import print_function
import torch

In [2]:
# initiailzation 되지 않은 5 x 3행렬 생성
x = torch.empty(5, 3)
print(x)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 1.5638e-42, 0.0000e+00],
        [0.0000e+00, 4.1051e-41, 0.0000e+00]])


In [3]:
# random initialization 된 행렬
x = torch.randn(5,3)
print(x)

tensor([[-0.1092,  0.5737,  0.5639],
        [ 1.5998,  0.5411, -0.1218],
        [ 0.6129, -0.8676, -0.0348],
        [-0.5847, -1.4523,  0.5565],
        [-0.3611,  1.3934, -0.4347]])


In [4]:
# dtype이 long이고 0으로 채워진 행렬
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
# 데이터로부터 tensor를 직접 생성
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


# 2. Autograd

- autograd 패키지는 Tensor의 모든 연산에 대해 자동 미분을 제공

## 2.1. Tensor
- requires_grad=True로 설정하면 해당 tensor의 모든 연산을 추적함.
  - .backward()를 사용해 모든 gradient를 자동 계산. 이 Tensor의 gradients는 .grad 속성에 누적됨
  - .grad_fn : 연산의 결과로 나온 Tensor가 가지는 속성으로, 자기 자신을 생성한 Function을 참조.
  - .detach() : 기록 추적 중단 
  
- with torch.no_grad(): 모델 평가시
  

In [6]:
import torch
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [7]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


y는 연산 결과로 나온 것이므로 grad_fn을 갖는다.

In [8]:
print(y.grad_fn)

In [9]:
z = y * y + 3
out = z.mean()

print(z, out)

tensor([[12., 12.],
        [12., 12.]], grad_fn=<AddBackward0>) tensor(12., grad_fn=<MeanBackward1>)


- 메서드 뒤에 \_가 붙으면 inplace 옵션으로 실행, 값을 바꿔치기한다.  
ex) .required_grad_(...)

In [10]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


## 3. Gradient

In [11]:
out.backward()

gradient d(out)/dx 를 출력

In [12]:
print(x.grad)

tensor([[1.5000, 1.5000],
        [1.5000, 1.5000]])


In [13]:
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2
print(y)

tensor([-400.7314,  850.1230,  483.3089], grad_fn=<MulBackward0>)


with torch.no_grad(): 를 이용하여 autograd가 .requires_grad=True인 Tensor들의 연산 기록을 추적하는 것을 멈출 수 있다.

In [14]:
print(x.requires_grad)
print((x ** 2).requires_grad)

# no_grad: test할 때 사용
with torch.no_grad():
    # test code
    print((x ** 2).requires_grad)

True
True
False
