In [1]:
import numpy as np

In [2]:
def linear(X, W):
    H = np.dot(X, W)
    
    return H

In [3]:
def sigmoid(H):
    p = 1 / (1 + np.exp(-H))
    
    return p

In [4]:
X = np.array([1, 2])

In [5]:
W = np.array([2, 3])

In [6]:
H = linear(X, W)
print(H)
p = sigmoid(H)
print(p)

8
0.99966464987


In [7]:
W = np.array([-4, -3])

In [8]:
H = linear(X, W)
print(H)
p = sigmoid(H)
print(p)

-10
4.53978687024e-05


In [9]:
from sklearn.datasets import load_iris

In [10]:
data = load_iris()

In [11]:
x = data["data"]
y = data["target"]

In [12]:
x[:10]

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1]])

In [13]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [14]:
class Softmax:
    def __init__(self):
        
        self.params = {}
        self.params['W'] = 0.0001 * np.random.randn(4, 3)
        self.params['b'] = np.ones(3)
    
    def forward(self, X):
        W = self.params['W']
        b = self.params['b']

        h = np.dot(X, W) + b
        a = np.exp(h)
        #stable_a = np.exp(h - np.max(h, axis = 1).reshape(-1,1))
        p = a/np.sum(a, axis = 1).reshape(-1,1)
        
        return p
    
    def loss(self, X, T):
        
        p = self.forward(X)
        
        n = T.shape[0]
        log_likelihood = 0
        log_likelihood -= np.log(p[np.arange(n), T]).sum()
        Loss = log_likelihood / n

        return Loss
    
    def accuracy(self, X, T):
        p = self.forward(X) #예측
        predict = np.argmax(p, axis = 1) #예측 결과 index 1darray 로 출력 
        
        return 1 - np.count_nonzero(predict - T)/len(T)
        
    def gradient(self, X, T, learning_rate = 0.0001):
        
        p = self.forward(X)
        
        t = np.zeros((T.shape[0], 3))
        t[np.arange(T.shape[0]), T] = 1
        #t는 인덱스 레이블 T를 One hot 벡터로 바꾼 것
        
        dp = p.copy()
        dp[np.arange(len(T)), T] -= 1
        dp /= len(T)
        
        #목적함수에 대한 가중치 미분값을 담을 zero array 생성
        grads = {}
        grads['W'] = np.zeros((4, 3))
        grads['b'] = np.zeros(10)
        #목적함수에 대한 가중치 미분값 합 구하기
        grads['W'] = np.dot(X.T, (p-t)/len(T))
        grads['b'] = np.sum((p-t)/len(T), axis = 0)
        #p-t 대신 dp 사용 가능
        
        self.params['W'] -= learning_rate * grads['W']
        self.params['b'] -= learning_rate * grads['b']

In [15]:
softmax = Softmax()

In [17]:
for i in range(50000):
    softmax.gradient(x, y)
    
    if i % 1000 == 0:
        print(i, "번째 학습중입니다.")
        print("Accuracy : ", softmax.accuracy(x, y))
        print("Loss :     ", softmax.loss(x, y))
        print(softmax.params['W'])

0 번째 학습중입니다.
Accuracy :  0.6666666666666667
Loss :      0.837258789697
[[ 0.04489043 -0.00302755 -0.04177102]
 [ 0.13593987 -0.05260227 -0.08335439]
 [-0.21403781  0.06099198  0.15326508]
 [-0.09858452  0.01258931  0.08602048]]
1000 번째 학습중입니다.
Accuracy :  0.6666666666666667
Loss :      0.804785146931
[[ 0.05509918 -0.0032708  -0.05173652]
 [ 0.15963724 -0.06165687 -0.09799717]
 [-0.24691491  0.07084157  0.17629261]
 [-0.11392999  0.01406223  0.09989303]]
2000 번째 학습중입니다.
Accuracy :  0.6666666666666667
Loss :      0.776127383534
[[ 0.06448324 -0.00321122 -0.06118015]
 [ 0.18178077 -0.07015501 -0.11164256]
 [-0.27785428  0.08007122  0.19800232]
 [-0.12834075  0.01524657  0.11311946]]
3000 번째 학습중입니다.
Accuracy :  0.6666666666666667
Loss :      0.750718923069
[[ 0.07314435 -0.00288925 -0.07016323]
 [ 0.20252399 -0.07813882 -0.12440196]
 [-0.30701452  0.08870293  0.21853085]
 [-0.14189688  0.01615592  0.12576624]]
4000 번째 학습중입니다.
Accuracy :  0.6666666666666667
Loss :      0.728079564684
[[ 0.

37000 번째 학습중입니다.
Accuracy :  0.9066666666666666
Loss :      0.470579237753
[[ 0.21258203  0.05810015 -0.27059031]
 [ 0.56350654 -0.20906522 -0.35445811]
 [-0.82554003  0.19886919  0.6268901 ]
 [-0.37988541 -0.03083886  0.41074954]]
38000 번째 학습중입니다.
Accuracy :  0.9066666666666666
Loss :      0.467382067874
[[ 0.21500368  0.06028072 -0.27519254]
 [ 0.56987039 -0.21102876 -0.35885842]
 [-0.83460558  0.19960187  0.63522297]
 [-0.38401672 -0.03315646  0.41719845]]
39000 번째 학습중입니다.
Accuracy :  0.92
Loss :      0.464271523547
[[ 0.21738785  0.06246177 -0.27975776]
 [ 0.57612614 -0.21294092 -0.36320201]
 [-0.84350715  0.2002707   0.64345571]
 [-0.38807314 -0.03549151  0.42358992]]
40000 번째 학습중입니다.
Accuracy :  0.92
Loss :      0.461242838773
[[ 0.21973629  0.0646427  -0.28428713]
 [ 0.58227841 -0.21480378 -0.36749142]
 [-0.85225159  0.20087872  0.65159212]
 [-0.39205784 -0.03784271  0.42992582]]
41000 번째 학습중입니다.
Accuracy :  0.92
Loss :      0.458291615896
[[ 0.22205065  0.06682293 -0.28878172]
