# Simple Naive Bayes Classifier
* Viagra 단어가 들어간 메일을 Spam로 분류하는 Simple Naive Bayes Classifier를 구현합니다.
* 하나하나 따라해주세요.

In [1]:
from pandas import Series, DataFrame
import pandas as pd
import numpy as np

In [2]:
# Example from - https://chrisalbon.com/python/pandas_map_values_to_values.html

viagra_spam = {'viagra': [1,0,0,0,0,0,0,0,1,1,1,0,0,1,0,0,0,0,0,1],
               'spam':[
                   1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,1,1,1
               ]} 
viagra_spam #

{'viagra': [1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1],
 'spam': [1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1]}

In [3]:
df = pd.DataFrame(viagra_spam, columns = ['viagra', 'spam'])
df.head()

viagra  spam
0       1     1
1       0     0
2       0     0
3       0     0
4       0     0

In [4]:
np.data = df.as_matrix() # as_matcix()함수를 통해 dataframe을 np-array로 변환해줍니다.
                         # return값은 np-matrix가 아니라 np-array입니다.
np.data

C:\Users\Saeyoon Lee\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


array([[1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 0],
       [1, 1],
       [1, 0],
       [1, 0],
       [0, 0],
       [0, 0],
       [1, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 1],
       [1, 1]], dtype=int64)

# Spam Filter 만들기

## P(viagra)

In [5]:
# P(viagra)
p_viagra = sum(np.data[:,0] == 1) / len(np.data)
p_viagra

0.3

#####  boolean index가 뭘까요?

In [6]:
# boolean index
# what is boolean index?
np.data[:, 0] == 1

array([ True, False, False, False, False, False, False, False,  True,
        True,  True, False, False,  True, False, False, False, False,
       False,  True])

In [7]:
np.data[:, 1] == 1

array([ True, False, False, False, False, False,  True, False,  True,
       False, False, False, False, False, False, False, False,  True,
        True,  True])

In [8]:
(np.data[:, 0] == 1) & (np.data[:, 1] == 1)

array([ True, False, False, False, False, False, False, False,  True,
       False, False, False, False, False, False, False, False, False,
       False,  True])

### P(viagra), P(spam), P(v_cap_s), P(n_v_cap_s)

In [9]:
# P(viagra), P(spam)
p_viagra = sum(np.data[:, 0] == 1) / len(np.data)
p_spam = sum(np.data[:, 1] == 1) / len(np.data)

# p_v_cap_s: viagra와 spam의 교집합.
p_v_cap_s = sum((np.data[:, 0] == 1) & (np.data[:, 1] == 1)) / len(np.data)
p_n_v_cap_s = sum((np.data[:, 0] == 0) & (np.data[:, 1] == 1)) / len(np.data)
# 비아그라가 안들어갔을 떄 스팸일 확률

In [10]:
# P(spam | viagra)

# First
# P(spam | viagra) =  P(p_v_cap_s) / P(viagra)
p_spam_viagra = p_v_cap_s / p_viagra
p_spam_viagra

0.5

In [11]:
# Second
p_spam * (p_v_cap_s / p_spam) / p_viagra

0.5

In [12]:
# P(spam | ~viagra)

# First
p_n_v_cap_s / (1 - p_viagra)

0.2142857142857143

In [13]:
# Second
p_spam * (p_n_v_cap_s / p_spam)  / (1 - p_viagra)

0.2142857142857143