# German Credit Dataset
- 대출인지 아닌지를 예측하는 문제
- 데이터를 NB에 맞도록 간단하게 변환합니다.
- Binary 데이터들로 이루어진 대출 사기 데이터들로 부터 대출인지 아닌지 예측해보세요.

In [1]:
from pandas import Series, DataFrame
import pandas as pd
import numpy as np

In [2]:
data_url = './fraud.csv'
df = pd.read_csv(data_url, sep=',')
df.head()

ID  History CoApplicant Accommodation  Fraud
0   1  current        none           own   True
1   2     paid        none           own  False
2   3     paid        none           own  False
3   4     paid   guarantor          rent   True
4   5  arrears        none           own  False

In [3]:
# ID열을 삭제해줍니다.
del df["ID"] 

# Label(Y_data)을 따로 저장해 줍니다.
Y_data = df.pop("Fraud")

In [4]:
# as_matrix()함수를 통해 array형태로 변환시켜 줍니다.
# Convert the frame to its Numpy-array representation.
# https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.as_matrix.html

Y_data = Y_data.as_matrix()
Y_data

C:\Users\Saeyoon Lee\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """


array([ True, False, False,  True, False,  True, False, False, False,
        True, False,  True,  True, False, False, False, False, False,
       False, False])

In [5]:
type(Y_data)

numpy.ndarray

In [6]:
df.head()

History CoApplicant Accommodation
0  current        none           own
1     paid        none           own
2     paid        none           own
3     paid   guarantor          rent
4  arrears        none           own

In [7]:
# 우리가 앞으로 사용할 데이터 셋입니다. 그런데 문제가 있어보이네요...

## One-Hot encoding

* 범주형 변수를 dummy변수로 변환해주는 작업
* Do it yourself!

### 1. Do One-Hot Encoding! 

In [8]:
# 범주형 변수 처리 문제입니다.
# 앞선 EDA 시간과 Logistic EDA를 통해 우리는 범주형 변수를 처리해 주는 방법을 배웠습니다.
# get_dummies를 사용해서 One-Hot encoding 처리를 해주세요.

x_df = pd.get_dummies(df)
x_df.head() # dummy변수로 변환

History_arrears  History_current  History_none  History_paid  \
0                0                1             0             0   
1                0                0             0             1   
2                0                0             0             1   
3                0                0             0             1   
4                1                0             0             0   

   CoApplicant_coapplicant  CoApplicant_guarantor  CoApplicant_none  \
0                        0                      0                 1   
1                        0                      0                 1   
2                        0                      0                 1   
3                        0                      1                 0   
4                        0                      0                 1   

   Accommodation_free  Accommodation_own  Accommodation_rent  
0                   0                  1                   0  
1                   0                  1                   0  
2                   0                  1                   0  
3                   0                  0                   1  
4                   0                  1                   0

* One-Hot Encoding이 제대로 되었다면 우리는 10개의 Feature를 얻을 수 있습니다.

In [9]:
x_data = x_df.as_matrix()
x_data

C:\Users\Saeyoon Lee\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


array([[0, 1, 0, 0, 0, 0, 1, 0, 1, 0],
       [0, 0, 0, 1, 0, 0, 1, 0, 1, 0],
       [0, 0, 0, 1, 0, 0, 1, 0, 1, 0],
       [0, 0, 0, 1, 0, 1, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 1, 0, 1, 0],
       [1, 0, 0, 0, 0, 0, 1, 0, 1, 0],
       [0, 1, 0, 0, 0, 0, 1, 0, 1, 0],
       [1, 0, 0, 0, 0, 0, 1, 0, 1, 0],
       [0, 1, 0, 0, 0, 0, 1, 0, 0, 1],
       [0, 0, 1, 0, 0, 0, 1, 0, 1, 0],
       [0, 1, 0, 0, 1, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 0, 1, 0, 1, 0],
       [0, 1, 0, 0, 0, 0, 1, 0, 0, 1],
       [0, 0, 0, 1, 0, 0, 1, 0, 1, 0],
       [1, 0, 0, 0, 0, 0, 1, 0, 1, 0],
       [0, 1, 0, 0, 0, 0, 1, 0, 1, 0],
       [1, 0, 0, 0, 1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 1, 1, 0, 0],
       [1, 0, 0, 0, 0, 0, 1, 0, 1, 0],
       [0, 0, 0, 1, 0, 0, 1, 0, 1, 0]], dtype=uint8)

In [10]:
# one-hot encoding을 통해 10개의 Feature를 얻었다.

#### Q1. as_matrix()함수를 통해 우리가 하고자 하는 것은 무엇일까요? 

In [18]:
# as_matcix()함수를 통해 dataframe을 np-array로 변환해줍니다.

In [11]:
Y_data == True # boolean index

array([ True, False, False,  True, False,  True, False, False, False,
        True, False,  True,  True, False, False, False, False, False,
       False, False])

In [12]:
len(set(Y_data))

2

## Naive bayes classifier

* P(Y)
* P(X1, X2, ..., Xn)
* P(Y|X1, X2, X3, ..., Xn)
* P(X1|Y), P(X2|Y), ... P(Xn|Y)
등 우리가 구해야 할 식들에 대한 아이디어가 있어야 합니다.

### P(Y1), P(Y0) 구하기

In [13]:
# P(Y1), P(Y0)
# P(Y1) = count(Y1) / count(Y)

P_Y_True = sum(Y_data==True) / len(Y_data)
P_Y_False = 1 - P_Y_True

P_Y_True, P_Y_False

(0.3, 0.7)

* 이번 튜토리얼에서는 **index를 이용합니다.**
* 이해하기보다는 따라 하면서 음미해보세요.

In [14]:
# y가 1일 경우, y가 0일 경우를 구해줘야 합니다.
# 이번 시간에는 np.where를 사용합니다.
# np.where

In [15]:
ix_Y_True = np.where(Y_data) # Y_data == True인 인덱스를 뽑아줍니다.
ix_Y_False = np.where(Y_data==False)

ix_Y_True, ix_Y_False

((array([ 0,  3,  5,  9, 11, 12], dtype=int64),),
 (array([ 1,  2,  4,  6,  7,  8, 10, 13, 14, 15, 16, 17, 18, 19],
        dtype=int64),))

In [16]:
# np.where을 사용해서 Y가1일 때와 0일 때 각각의 인덱스 값을 얻을 수 있게 되었습니다.

In [17]:
# P(X|Y) = count(X_cap_Y) / count(Y)

### productP(X|Yc) 구하기

* product * P(X|Y1)
* product * P(X|Y2)

In [20]:
# p_x_y_true = count(X_cap_Y_true) / count(Y_true)
p_x_y_true = (x_data[ix_Y_True].sum(axis=0) / sum(Y_data==True))  # Q.뒤에 sum(Y_data == True) 필요한가요? # 앞에 식이 P(X_cap_Y1)인 것 같은데...
p_x_y_false = (x_data[ix_Y_False].sum(axis=0) / sum(Y_data==False))

p_x_y_true, p_x_y_false

(array([0.16666667, 0.5       , 0.16666667, 0.16666667, 0.        ,
        0.16666667, 0.83333333, 0.        , 0.66666667, 0.33333333]),
 array([0.42857143, 0.28571429, 0.        , 0.28571429, 0.14285714,
        0.        , 0.85714286, 0.07142857, 0.78571429, 0.14285714]))

In [21]:
# 총 10개의 값에 대해서 확률을 구해준다.

In [39]:
x_test = [0,1,0,0,0,1,0, 0,1,0]

import math

p_y_true_test = P_Y_True * p_x_y_true.dot(x_test)
p_y_false_test = P_Y_False * p_x_y_false.dot(x_test)

p_y_true_test, p_y_false_test

(0.42, 0.8166666666666665)

In [40]:
P_Y_True

0.3

In [42]:
p_y_true_test > p_y_false_test

False

## 2. Do Smoothing을 통해 P(Y=1|X)의 확률과 P(Y=0|X)의 확률 값을 비교하세요.

In [43]:
smoothing_p = 2

p_x_y_true = (x_data[ix_Y_True].sum(axis=0) + smoothing_p) / (sum(Y_data==True) + smoothing_p * len(set(Y_data)))
p_x_y_false = (x_data[ix_Y_False].sum(axis=0) + smoothing_p) / (sum(Y_data==False) + smoothing_p * len(set(Y_data)))

p_x_y_true, p_x_y_false

(array([0.3, 0.5, 0.3, 0.3, 0.2, 0.3, 0.7, 0.2, 0.6, 0.4]),
 array([0.44444444, 0.33333333, 0.11111111, 0.33333333, 0.22222222,
        0.11111111, 0.77777778, 0.16666667, 0.72222222, 0.22222222]))

In [44]:
import math
x_test = [0,1,0,0,0,1,0,0,1,0]

p_y_true_test = np.log(P_Y_True) + np.log(p_x_y_true.dot(x_test))
p_y_false_test = np.log(P_Y_False) + np.log(p_x_y_false.dot(x_test))

p_y_true_test, p_y_false_test

(-0.8675005677047232, -0.20252426411147428)

In [45]:
p_y_true_test > p_y_false_test

False

# 결과값에 대한 설명과 해석을 달아주세요

In [31]:
# 너무 많은 확률 값을 가졌을 떄 확률값이 0에 수렴하게 되는 문제가 발생하게 되므로
# 곱하지 않고 log를 취해 더해주고
# 스무딩을 통해 작게나마 확률이 나올 수 있도록 변경해주었다.

In [32]:
# 그 결과 p_y_false_test의 확률이 더 크게 나왔으므로
# test data의 Fraud는 False로 분류할 수 있다.